<?php

namespace AbonnementBundle\Repository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AbonnementRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall($modePaiement)
    {
        $query = $this->getEntityManager()->createQuery("select a from AbonnementBundle:Abonnement a where a.modePaiement='$modePaiement' ");
        return $query->getResult();
    }
}
