abonnement_homepage:
    path:     /
    defaults: { _controller: AbonnementBundle:Default:index }

read:
    path:     /readv
    defaults: { _controller: AbonnementBundle:AbonnementCrud:read }

readc:
    path:     /readc
    defaults: { _controller: AbonnementBundle:AbonnementCrud:readc }

create:
    path:     /createv
    defaults: { _controller: AbonnementBundle:AbonnementCrud:create }

delete:
    path:     /deletev/{nCartemembre}
    defaults: { _controller: AbonnementBundle:AbonnementCrud:delete }

update:
    path:     /updatev/{nCartemembre}
    defaults: { _controller: AbonnementBundle:AbonnementCrud:update }

search_Mode:
    path:     /search
    defaults: { _controller: AbonnementBundle:AbonnementCrud:search_Mode }

read_e:
    path:     /read
    defaults: { _controller: AbonnementBundle:AbonnementExtraCrud:read }

create_e:
    path:     /create
    defaults: { _controller: AbonnementBundle:AbonnementExtraCrud:create }

delete_e:
    path:     /delete/{nCartemembre}
    defaults: { _controller: AbonnementBundle:AbonnementExtraCrud:delete }

update_e:
    path:     /update/{nCartemembre}
    defaults: { _controller: AbonnementBundle:AbonnementExtraCrud:update }

sandbox_pdfexample:
    path:     /pdf-example/{nCartemembre}
    defaults: { _controller: AbonnementBundle:AbonnementCrud:pdf }

sandbox_pdfexample1:
    path:     /pdf-example1
    defaults: { _controller: AbonnementBundle:AbonnementExtraCrud:pdf }

_graphePie:
    path:     /pie
    defaults: { _controller: AbonnementBundle:AbonnementCrud:graphe }