<?php

namespace AbonnementBundle\Repository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AbonnementRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall($modePaiement)
    {
        $query = $this->getEntityManager()->createQuery("select a from AbonnementBundle:Abonnement a where a.modePaiement like :modePaiement ");
        $query->setParameter(":modePaiement",'%'.$modePaiement.'%');
        return $query->getResult();
    }
    public function stat1()
    {
    $query1 = $this->getEntityManager()->createQuery("select count(b.nCartemembre) AS nm from AbonnementBundle:Abonnement b where b.dureeAbonnement = :i ");
    $query1->setParameter(':i', "3 mois");
      return $query1->getResult();
    }
    public function stat2()
    {
     $query2 = $this->getEntityManager()->createQuery("select count(d.nCartemembre) AS nm from AbonnementBundle:Abonnement d where d.dureeAbonnement = :j ");
        $query2->setParameter(':j', "6 mois");
        return $query2->getResult();
    }
    public function stat3()
    {
     $query3 = $this->getEntityManager()->createQuery("select count(e.nCartemembre) AS nm from AbonnementBundle:Abonnement e where e.dureeAbonnement = :k ");
        $query3->setParameter(':k', "1 an");
        return $query3->getResult();
    }
}
